### ISSUE TITLE
Filter on trackName in ApiSpotifyService

### ISSUE THREAD

**Issue by carstenflokstra** [PiekJ/jambot#102]
Add trackname to this stream as filter to prevent wrong songs being found. Just in case
https://github.com/PiekJ/jambot/blob/2e860d0f4e7e52eef5a4b07a064cd8ba22942fde/src/main/java/dev/joopie/jambot/api/spotify/ApiSpotifyService.java#L87-L91

**Comment by mslowiak** [comment]
@carstenflokstra 
Can I pick this up?

**Comment by carstenflokstra** [comment]
@mslowiak Sure! Go ahead. Let me know if you need any help :)
