### ISSUE TITLE
Let other developers restart the bot on the server

### ISSUE THREAD

**Issue by carstenflokstra** [PiekJ/jambot#15]
### Why
Sometimes the bot will have a state where it is no longer available. In order to solve this, a restart could be sufficient to do. Now, only @PiekJ can restart the bot on his own hosted instance.

### What
It would be cool if the rest of the developers that have access to this repo can also restart the bot in case @PiekJ isn't available. 

### How
Maybe we can create a Github Action to restart the bot via somekind of a webhook. Or we can create an admin panel hosted somewhere we can login via our Github Accounts.

**Comment by PiekJ** [comment]
This is now resolved. Collabs can start a deploy from GitHub Actions.
